config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  mount ActionCable.server => '/cable'

  resources :chatrooms
  resources :messages
  resource :list, only: [:show]
  resource :item, only: [:create, :destroy]

  root 'lists#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :topic, presence: true, uniqueness: true, cas_sensitive: false
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  belongs_to :user

  before_save :assign_name, if: :user

  private

  def assign_name
    self.name = user.name
  end
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :timeoutable,
    :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:google_oauth2]

  has_many :user_omniauths

  has_many :messages
  has_many :chatroom, through: :messages
  has_many :items
  validates :name, presence: true, uniqueness: true

  def self.from_omniauth!(auth)
    joins(:user_omniauths).where(user_omniauths: { provider: auth.provider, uid: auth.uid }).first_or_create! do |user|
      user.user_omniauths.build(provider: auth.provider, uid: auth.uid)
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/models/user_omniauth.rb
class UserOmniauth < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true

  private

  def after_sign_out_path_ofr(resource_or_scope)
    chatrooms_path
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.all
  end

  def new
    @chatroom = Chatroom.new
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save
      render @chatroom
    else
      redirect_back(fallback_location: new_chatroom_url)
    end
  end

  def show
    @chatroom = Chatroom.find_by(id: params[:id])
    @message = Message.new
  end

  def chatroom_params
    params.require(:chatroom).permit(:topic)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #xoxb-66734971440-vDCyCHjPD9s5ofslVyjE2mUn
  before_action :authenticate_user!

  def create
    list = List.last || List.create!
    item = Item.create!(params_for_create.merge({ list: list, user: current_user }))

    ActionCable.server.broadcast 'items',
      action: 'create',
      template: render(partial: 'lists/list_item', locals: { item: item })
  end

  def destroy
    item = current_user.items.find(params_for_destroy)
    item.destroy!
    ActionCable.server.broadcast 'items',
      action: 'destroy',
      item: { id: item.id }
    head :ok
  end

  private

  def params_for_destroy
    params.require(:item).permit(:id).fetch(:id)
  end

  def params_for_create
    params.require(:item).permit(:content, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def show
    @list = List.last || List.create!
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = Message.new(message_params)
    message.user = User.first
    if message.save
      ActionCable.server.broadcast 'messages',
        message: message.body,
        user: message.user.name
      head :ok
    else
      render json: message.errors
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :chatroom_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth!(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end

  def failure_message
    "Invalid login"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def mapped_omniauth(provider)
    map = { :google_oauth2 => "Google" }
    map.fetch(provider)
  end

  def user_firstname
    current_user.email.match(/^(.*)\..*@/)[1]
  end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chatrooms/_chatroom.html.erb
<%= chatroom.topic %>

<%= link_to 'back', chatrooms_url %>

app/views/chatrooms/_form.html.erb
<%= form_for @chatroom do |f| %>
  <%= f.label :topic %>
  <%= f.text_field :topic %>
  <%= f.submit 'create' %>
<% end %>

app/views/chatrooms/index.html.erb
<ul>
  <% @chatrooms.each do |chatroom| %>
    <li>
      <%= link_to chatroom.topic, chatroom_url(chatroom) %>
    </li>
  <% end %>
</ul>

<%= link_to 'new room', new_chatroom_url %>

app/views/chatrooms/new.html.erb
<%= render 'form' %>

app/views/chatrooms/show.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1><%= @chatroom.topic %></h1>

  <div class="panel panel-default">
    <% if @chatroom.messages.any? %>
      <div class="panel-body" id="messages">
        <%= render partial: 'messages/message', collection: @chatroom.messages%>
      </div>
    <%else%>
      <div class="panel-body hidden" id="messages">
      </div>
    <%end%>
  </div>

  <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}%>
</div>

<a href="#">#</a>

app/views/items/_form.html.erb
<%= form_for :item, url: item_url, remote: true do |f| %>
  <%= f.text_field :content, class: 'text-input', placeholder: 'content' %>

  <%= f.text_field :comment, class: 'text-input', placeholder: 'comment' %>

  <%= button_tag '', id: 'submit-new-item', class: 'fab bg-green-500 color-white small' do %>
    <i class="icon-check"></i>
  <% end %>
<% end %>

app/views/items/_item.html.erb
<div ripple style='width: 100%'>
  <% image_url = 'https://pbs.twimg.com/profile_images/514741347832459264/91rhOB8I_400x400.png' %>
  <img class='item-icon' src="<%= image_url %>" alt=""/>
  <span class='item-text'>
    <%= item.name %>
    <span class='secondary-text color-orange-500'>
      <%= item.content %>
      <span class='secondary-text'><%= item.comment %></span>
    </span>
  </span>
</div>
<% if current_user == item.user %>
  <%= button_to item_path, action: 'delete', remote: true,
    method: :delete, data: { confirm: 'Are you sure?' }, params: { item: { id: item } },
    class: 'button', style: 'height: 100%' do %>
    <i class="icon-cancel color-red-500"></i>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinSensation</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='notification'>
      <% if notice %>
        <div class="toast">
          <label class="toast-label"><%= notice %></label>
        </div>
      <% end %>
      <% if alert %>
        <div class="toast">
          <label class="toast-label"><%= alert %></label>
        </div>
      <% end %>
    </div>
    <% if current_user %>
      <div class='session-panel'>
        <%= user_firstname.capitalize %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lists/_list.html.erb
<ul class='list' id='list'>
  <% list.items.reverse.each do |item| %>
    <%= render 'list_item', item: item %>
  <% end %>
</ul>

app/views/lists/_list_item.html.erb
<li name='item_<%= item.id %>'><%= render item %></li>
<li name='item_<%= item.id %>' class='divider'></li>

app/views/lists/show.html.erb
<div>
  <div style='text-align: center; width: 100%;'>
    <%= render '/items/form' if current_user %>
  </div>
  <div  style='max-width: 600px; margin: 0 auto;'>
    <%= render @list %>
  </div>
</div>

app/views/messages/_message.html.erb
<p>
  <b>
    <%= message.user.name %>:
  </b>
  <%= message.body %>
</p>

app/views/messages/_message_form.html.erb
<%= form_for message, remote: true, authenticity_token: true do |f| %>
  <%= f.label :your_message %>:
  <%= f.text_area :body, class: "form-control", data: {textarea: "message"}%>

  <%= f.hidden_field :chatroom_id, value: chatroom.id %>
  <%= f.submit "send", class: "btn btn-primary", data: {send: "message"}%>
<% end %>